name: Fetch Twitter Feature Flags

on:
  schedule:
    - cron: '*/20 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-flags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
    - name: Run fetcher
      run: npm run fetch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push changes
      run: |
        git add public/twitter-feature-flags.json public/raw-twitter-feature-flags.json
        git commit -m "Update feature flags" || echo "No changes to commit"
        git push origin main